apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-app
spec:
  type: NodePort  # Changed from ClusterIP to access from browser
  selector:
    app: flask
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30007  # Kubernetes will assign if not specified
